language: csharp
sudo: false # faster builds
dist: xenial
notifications:
  email: false
before_install:
  - git lfs pull
install:
  - dotnet restore ./
mono: none
dotnet: 2.2
script:
  - dotnet restore ./
  - cd tests/
  - dotnet test
